# Generated by Django 5.1.7 on 2025-04-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='num_ratings',
            field=models.FloatField(default=0.0),
        ),
    ]
