# Generated by Django 5.1.7 on 2025-04-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user_id', 'mobile', 'street_address', 'zip_code')},
        ),
    ]
