# Generated by Django 5.1.7 on 2025-04-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
